name: Build_ImageBuilder

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          选择 OpenWrt 分支
        required: true
        default: "immortalwrt"
        type: choice
        options:
          - immortalwrt
          - openwrt
          
      device:
        description: |
          选择 imageBuilder 镜像和型号
        required: true
        default: "x86-64_generic"
        type: choice
        options:
          - x86-64_generic
          
      version:
        description: |
          选择 OpenWrt 版本
        required: true
        default: "24.10.5"
        type: choice
        options:
          - "24.10-SNAPSHOT"
          - "24.10.5"
          - "24.10.4"
          - "24.10.3"
          - "24.10.2"
          - "24.10.1"
          - "24.10.0"
          - "23.05.5"
          
      rootfs_partsize:
        description: |
          设置软件包大小 单位(MB)
        required: true
        default: '1024'
        type: choice
        options:
          - 512
          - 1024
          - 2048
          
      network_lan:
        description: |
          设置固件IP地址
        required: true
        default: '10.10.10.10'
        type: choice
        options:
          - "10.10.10.10"
          
     diy_package:
        description: |
          设置Diy插件网址
        required: true
        default: 'all'
        type: choice
        options:
          - "https://raw.githubusercontent.com/3wxhn/Actions-Build_ImmortalWrt/refs/heads/main/x86-64.env"
          
      diy_script:
        description: |
          设置Diy初始化脚本网址
        required: true
        default: 'all'
        type: choice
        options:
          - "https://raw.githubusercontent.com/3wxhn/Actions-Build_ImmortalWrt/refs/heads/main/x86-64.sh"
          
      docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: false
        type: boolean
        
      enable_pppoe:
        description: |
          是否默认PPPoE协议?
        required: true
        default: true
        type: boolean
        
      pppoe_account:
        description: |
          是否添加 宽带账号? (可留空)
        required: false
        default: '123'
      pppoe_password:
        description: |
          是否添加 宽带密码? (可留空)
        required: false
        default: '123'
        
jobs:
  Call_ImageBuilder:
    uses: 3wlh/Actions-ImageaBuilder/.github/workflows/Call_ImageBuilder.yml@main
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      device: ${{ inputs.device }}
      version: ${{ inputs.version }}
      rootfs_partsize: ${{ inputs.rootfs_partsize }}
      network_lan: ${{ inputs.network_lan }}
      docker: ${{ inputs.docker }}
      enable_pppoe: ${{ inputs.enable_pppoe }}
      pppoe_account: ${{ inputs.pppoe_account }}
      pppoe_password: ${{ inputs.pppoe_password }}
      diy_package: ${{ inputs.diy_package }}
      diy_script: ${{ inputs.diy_script }}